{{- if (not .Values.configExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opengist.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opengist.labels" . | indent 4 }}
type: Opaque
stringData:
  config.yml: |-
    {{- .Values.config | toYaml | nindent 4 }}
{{- end }}