name: docker_images

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Debug Vars
        run: |
          echo "Variable NAME is: ${{ vars.NAME }}"
          # 绝对不要 echo ${{ secrets.TOKEN }} !!!
          if [ -z "${{ vars.NAME }}" ]; then
            echo "::error::Variable NAME is empty! Check your repository settings."
            exit 1
          fi
      - name: Generate Unique Tag
        id: meta_tag
        run: |
          DATE=$(date +'%Y%m%d')
          SHA=${{ github.sha }}
          SHORT_SHA=${SHA:0:7}
          echo "tag=v${DATE}-${SHORT_SHA}" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.NAME }}
          password: ${{ secrets.TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.NAME }}/opengist:${{ steps.meta_tag.outputs.tag }}
            ${{ vars.NAME }}/opengist:latest
